{"name": "test_get_user_by_id", "status": "failed", "statusDetails": {"message": "AssertionError: assert 500 == 200\n +  where 500 = <Response [500]>.status_code", "trace": "def test_get_user_by_id():\n        \"\"\"\n        finds user by id\n        :return:\n        \"\"\"\n        logging.info(\"finding user by id\")\n        response = requests.get(f\"{url}/user/a\", headers=header)\n>       assert response.status_code == 200\nE       assert 500 == 200\nE        +  where 500 = <Response [500]>.status_code\n\ntest.py:188: AssertionError"}, "description": "\n    finds user by id\n    :return:\n    ", "start": 1659615842656, "stop": 1659615843353, "uuid": "b608a680-b065-4f99-add2-34465e1abd82", "historyId": "584aa73ce5318c268fc17bbed80b8f72", "testCaseId": "44e54831ea0c75a54f2466fd130864cf", "fullName": "test#test_get_user_by_id", "labels": [{"name": "suite", "value": "test"}, {"name": "host", "value": "DESKTOP-V80V9RG"}, {"name": "thread", "value": "22264-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test"}]}